### PR TITLE
4 more data/info sources

### PR DESCRIPTION
**Pull request by mattosborn**

### CODE REVIEW

**Comment by jsvine** [comment]
Thanks, Matt! A couple of questions:
- It looks like the mosquito data/study you added is an earlier/nearly-identical version of the study already listed in this guide. (Same authors, same approach.) Or am I misunderstanding?
- The spread prediction paper is very interesting, but currently doesn't contain any structured data. I'm trying to get the data, but haven't received it yet. Do you happen to have the data, by any chance?

**Comment by mattosborn** [comment]
It looks like the mosquito distribution paper I added was written as a precursor to, or just one part of, the 'global compendium' paper. They both reference the same data. I think the source you already have is more complete though. I've removed the reference to that paper but have left the csv data in.

I don't think the data from the spread prediction paper is public and I haven't attempted to contact anyone for it.

**Comment by jsvine** [comment]
Thanks! Very helpful. Made a few edits here: https://github.com/BuzzFeedNews/zika-data/tree/pr-4
- Some language tweaks.
- Removed the mosquito CSV, since it's already easily available, stable, and well-documented, on Dryad.
- Waiting to include the spread-prediction paper until data from it is available.

Does that look good to you? If so, I'll merge that in and add you to the acknowledgements.

**Comment by mattosborn** [comment]
Yep looks good. Closing this PR.

**Pull request closed without merging**
